# Generated by Django 2.2.10 on 2020-02-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0002_categoria_comentario_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(related_name='carrinhos', to='aula5.Produto')),
            ],
        ),
    ]
