# Generated by Django 2.2.10 on 2020-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula11', '0005_destinatario_remetente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aula11.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
